# Generated by Django 4.1.4 on 2022-12-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_movies_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_movies_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='seen_movies_id',
            field=models.IntegerField(default=None),
        ),
    ]
