# Generated by Django 4.1.4 on 2022-12-10 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_alter_user_favorite_movies_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_movies_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_movies_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seen_movies_id',
        ),
        migrations.CreateModel(
            name='SeenMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
                ('seen_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('saved_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='saved_movies_id',
            field=models.ManyToManyField(to='userprofiles.savedmovie'),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_movies_id',
            field=models.ManyToManyField(to='userprofiles.seenmovie'),
        ),
    ]
