# Generated by Django 4.1.4 on 2022-12-14 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_remove_user_favorite_movies_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmovie',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seenmovie',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
