# Generated by Django 4.1.4 on 2022-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_movies_id',
            field=models.ManyToManyField(to='userprofiles.savedmovie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seen_movies_id',
            field=models.ManyToManyField(to='userprofiles.seenmovie'),
        ),
        migrations.AlterField(
            model_name='savedmovie',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_movies', to='userprofiles.profile'),
        ),
        migrations.AlterField(
            model_name='seenmovie',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_movies', to='userprofiles.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
