# Generated by Django 4.1.4 on 2022-12-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_seenmovie_length_alter_profile_saved_movies_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedmovie',
            old_name='saved_by',
            new_name='profiles',
        ),
        migrations.RenameField(
            model_name='seenmovie',
            old_name='seen_by',
            new_name='profiles',
        ),
    ]
