# Generated by Django 4.1.4 on 2022-12-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_rename_saved_by_savedmovie_profiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmovie',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
