# Generated by Django 4.1.4 on 2022-12-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='userprofiles.profile'),
            preserve_default=False,
        ),
    ]
